# Generated by Django 5.2.14 on 2026-05-24 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.CharField(blank=True, max_length=255)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('pages_viewed', models.JSONField(default=list)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('is_bot', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='documents.document')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
